language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
  - rm yarn.lock
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - npm run ci
